export const config = {
  nodeEnv: process.env.NODE_ENV || "development",
  port: Number(process.env.PORT || 8080),
  host: process.env.HOST || "0.0.0.0",
  serviceName: process.env.SERVICE_NAME || "salaopremiun-api",
  version: process.env.APP_VERSION || "0.1.0",
  apiAdminToken: process.env.API_ADMIN_TOKEN || "",
  apiSecret: process.env.API_SECRET || "",
  cronSecret: process.env.CRON_SECRET || "",
  dataDir: process.env.DATA_DIR || "./data",
  maxNdjsonLines: Number(process.env.MAX_NDJSON_LINES || 500),
  retentionDays: Number(process.env.RETENTION_DAYS || 7),
  supabaseUrl: process.env.SUPABASE_URL || "",
  supabaseAnonKey: process.env.SUPABASE_ANON_KEY || "",
  supabaseServiceRoleKey: process.env.SUPABASE_SERVICE_ROLE_KEY || "",
  asaasApiKey: process.env.ASAAS_API_KEY || "",
  asaasWebhookToken: process.env.ASAAS_WEBHOOK_TOKEN || "",
  resendApiKey: process.env.RESEND_API_KEY || "",
  webPushPrivateKey: process.env.WEB_PUSH_VAPID_PRIVATE_KEY || "",
  webPushPublicKey: process.env.NEXT_PUBLIC_WEB_PUSH_VAPID_PUBLIC_KEY || "",
};
